apiVersion: v1
kind: Service
metadata:
  name: fastapi-svc
  namespace: shitik-lab
spec:
  type: LoadBalancer
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
